In [19]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1 # 1 row, 3 columns: vector

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3],
              [4,5,6]])

a3 = ([[[1,2,3],
        [4,5,6],
        [7,8,9]]])

In [4]:
a2 # 2 rows, 3 columns: matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim, a2.ndim # number of dimensions

(1, 2)

In [10]:
a1.dtype

dtype('int64')

In [11]:
a1.size, a2.size # total number of elements in an array

(3, 6)

In [12]:
type(a1), type(a2) 

(numpy.ndarray, numpy.ndarray)

In [13]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating NumPy array

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [8]:
# returns an array of given shape and type, filles with ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones.dtype # default DataType

dtype('float64')

In [11]:
# returns an array of given shape and type, filles with zeros 
# (used as a placeholder array)
zeros = np.zeros((2, 3))
zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0, 10, 2) # (start, stop, step)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0,20, size=(3,5)) # (low, high)
random_array

array([[15,  0,  2,  8, 13],
       [ 3,  5, 17,  2, 19],
       [ 9,  1, 18, 12, 16]])

In [14]:
random_array.size

15

In [15]:
random_array.shape

(3, 5)

In [17]:
# array with (pseudo) random floats between 0 and 1
random_array_2 = np.random.random((5,3)) # shape
random_array_2

array([[0.98683658, 0.51706101, 0.18140538],
       [0.40243449, 0.38175186, 0.20340773],
       [0.35317929, 0.1957777 , 0.10292158],
       [0.097982  , 0.09843272, 0.51966936],
       [0.36383991, 0.0662233 , 0.28066361]])

In [18]:
# similar output
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.54285469, 0.65857383, 0.01859138],
       [0.36881526, 0.56695273, 0.16143781],
       [0.18819183, 0.70381319, 0.30515289],
       [0.00328164, 0.13202201, 0.51897628],
       [0.15361725, 0.70171503, 0.61036922]])

In [24]:
# Pseudo-random numbers
np.random.seed(seed=0) # seed can be any number
# array numbers are still "random", but reproducible 
# (rerunning produces the same array)
random_array_4 = np.random.randint(25, size=(3,3))
random_array_4

array([[12, 15, 21],
       [ 0,  3,  3],
       [ 7,  9, 19]])